import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nevan Samadhana Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="p-10 mb-12 flex justify-between">
            <h1 className="text-xl">developedByNev</h1>
            <ul className="flex items-center"> 
              <li>
                <BsFillMoonStarsFill className=' cursor-pointer text-xl'/>
                </li>
              <li><a className=" bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>

          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium">Nevan Samadhana</h2>
            <h3>Developer and Designer</h3>
            <p>Software developer currently in Seattle, Wa. Loves Basketball and cooking</p>
          </div>

          <div>
          <a href="https://www.linkedin.com/in/nsamadhana/"><AiFillLinkedin /></a>
          <a href="https://github.com/nsamadhana"><AiFillGithub /></a>
          </div>

        </section>
      </main>
    </>
  )
}
